### PR TITLE
removed counter

### PR DESCRIPTION
**Pull request by yathi**
I removed the global variable counter as it was not really needed. You would have to change convert_game_status(status). I think it is wrong. But I did not change it. Just look at it and let me know if you think its alright.

### CODE REVIEW

**Comment by mviz** [comment]
Hey Yathi,

I was with at my friend's cabin this weekend and didn't have reception.
I'll look into these changes, and I'll be in the office tomorrow.

**Comment by mviz** [comment]
Hey Yathi,

I just pushed some changes to git, can you give me some feedback on them?
I implemented the new game button, which works but only the first time. So
I can play two games in a row, but the third time it won't refresh, I'm
looking into fixing that. There will be an issue though, which is
eventually the list of names will run out of names of the list.
In terms of new faces, have you put more thought into where they images
will come from?
Also, is the side bad still needed? The colours probably don't make sense
to anyone else, because there's no legend. Do you want me to modify that?
Do you have an update for the contact me and about pages?

Some of the things I'm still looking to change are:
Disabling teh next step button in between animations so that people can't
spam it (as it messes with animations).
Fixing the HTML for the bars, so that the tops are in line with the top of
the images.

**Comment by yathi** [comment]
Hey Matt,

I would still like the list on the side with the colors. The different
colors for different actions do make sense a bit and they show that
something is changing.

I haven't been able to get better images yet.

The issue of running out with names can be easily fixed by reinitializing
the list of names at every restart. If you want me to do that let me know
and I can do that.

Like you said I got it working just twice. Do you know why is that?

Yathi

On 18 August 2014 15:13, mfritze notifications@github.com wrote:

> Hey Yathi,
> 
> I just pushed some changes to git, can you give me some feedback on them?
> I implemented the new game button, which works but only the first time. So
> I can play two games in a row, but the third time it won't refresh, I'm
> looking into fixing that. There will be an issue though, which is
> eventually the list of names will run out of names of the list.
> In terms of new faces, have you put more thought into where they images
> will come from?
> Also, is the side bad still needed? The colours probably don't make sense
> to anyone else, because there's no legend. Do you want me to modify that?
> Do you have an update for the contact me and about pages?
> 
> Some of the things I'm still looking to change are:
> Disabling teh next step button in between animations so that people can't
> spam it (as it messes with animations).
> Fixing the HTML for the bars, so that the tops are in line with the top of
> the images.
> 
> On Sun, Aug 17, 2014 at 3:45 PM, Matthew Fritze mfritze@ualberta.ca
> wrote:
> 
> > Hey Yathi,
> > 
> > I was with at my friend's cabin this weekend and didn't have reception.
> > I'll look into these changes, and I'll be in the office tomorrow.
> > On 16 Aug 2014 15:33, "Yathirajan BM" notifications@github.com wrote:
> > 
> > > I removed the global variable counter as it was not really needed. You
> > > would have to change convert_game_status(status). I think it is wrong.
> > > But
> > > I did not change it. Just look at it and let me know if you think its
> > > 
> > > ## alright.
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/Yathi/Integrated_Temp master
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/mfritze/Integrated_Temp/pull/3
> > > Commit Summary
> > > - removed counter
> > > 
> > > File Changes
> > > - _M_ surveys/views.py
> > >   https://github.com/mfritze/Integrated_Temp/pull/3/files#diff-0 (12)
> > > 
> > > Patch Links:
> > > - https://github.com/mfritze/Integrated_Temp/pull/3.patch
> > > - https://github.com/mfritze/Integrated_Temp/pull/3.diff
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/mfritze/Integrated_Temp/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mfritze/Integrated_Temp/pull/3#issuecomment-52556107.

## 

_Yathi_

**Comment by mviz** [comment]
Okay. Would you like me to make a legend so that people understand what's
going on? What about something that indicates the game status, because
sometimes no NPCs are moving, and it takes 4 button clicks to make
something change.

Alright.

I can do that, I just wasn't sure if you wanted to keep the finite list of
names as is.

I haven't figured it out. I have been able to get it to work as many as 4
times in a row. I think it may have to do with how quickly you press the
new game button but it's not consistent. I'm still looking into it. Do you
have any ideas?

**Comment by yathi** [comment]
Yes, I think a legend is a good idea.

Even I have been thinking about the 4 clicks to show a change when nothing
happens. But I don't have any ideas currently of what we could do about it.
Will think of something for that.

About the new game button I haven't fully looked into the code. I am not
sure. I'll check that and let you know. .

Yathi

On 19 August 2014 15:04, mfritze notifications@github.com wrote:

> Okay. Would you like me to make a legend so that people understand what's
> going on? What about something that indicates the game status, because
> sometimes no NPCs are moving, and it takes 4 button clicks to make
> something change.
> 
> Alright.
> 
> I can do that, I just wasn't sure if you wanted to keep the finite list of
> names as is.
> 
> I haven't figured it out. I have been able to get it to work as many as 4
> times in a row. I think it may have to do with how quickly you press the
> new game button but it's not consistent. I'm still looking into it. Do you
> have any ideas?
> On 19 Aug 2014 14:57, "Yathirajan BM" notifications@github.com wrote:
> 
> > Hey Matt,
> > 
> > I would still like the list on the side with the colors. The different
> > colors for different actions do make sense a bit and they show that
> > something is changing.
> > 
> > I haven't been able to get better images yet.
> > 
> > The issue of running out with names can be easily fixed by
> > reinitializing
> > the list of names at every restart. If you want me to do that let me
> > know
> > and I can do that.
> > 
> > Like you said I got it working just twice. Do you know why is that?
> > 
> > Yathi
> > 
> > On 18 August 2014 15:13, mfritze notifications@github.com wrote:
> > 
> > > Hey Yathi,
> > > 
> > > I just pushed some changes to git, can you give me some feedback on
> > > them?
> > > I implemented the new game button, which works but only the first
> > > time.
> > > So
> > > I can play two games in a row, but the third time it won't refresh,
> > > I'm
> > > looking into fixing that. There will be an issue though, which is
> > > eventually the list of names will run out of names of the list.
> > > In terms of new faces, have you put more thought into where they
> > > images
> > > will come from?
> > > Also, is the side bad still needed? The colours probably don't make
> > > sense
> > > to anyone else, because there's no legend. Do you want me to modify
> > > that?
> > > Do you have an update for the contact me and about pages?
> > > 
> > > Some of the things I'm still looking to change are:
> > > Disabling teh next step button in between animations so that people
> > > can't
> > > spam it (as it messes with animations).
> > > Fixing the HTML for the bars, so that the tops are in line with the
> > > top
> > > of
> > > the images.
> > > 
> > > On Sun, Aug 17, 2014 at 3:45 PM, Matthew Fritze mfritze@ualberta.ca
> > > wrote:
> > > 
> > > > Hey Yathi,
> > > > 
> > > > I was with at my friend's cabin this weekend and didn't have
> > > > reception.
> > > > I'll look into these changes, and I'll be in the office tomorrow.
> > > > On 16 Aug 2014 15:33, "Yathirajan BM" notifications@github.com
> > > > wrote:
> > > > 
> > > > > I removed the global variable counter as it was not really needed.
> > > > > You
> > > > > would have to change convert_game_status(status). I think it is
> > > > > wrong.
> > > > > But
> > > > > I did not change it. Just look at it and let me know if you think
> > > > > its
> > > > > 
> > > > > ## alright.
> > > > > 
> > > > > You can merge this Pull Request by running
> > > > > 
> > > > > git pull https://github.com/Yathi/Integrated_Temp master
> > > > > 
> > > > > Or view, comment on, or merge it at:
> > > > > 
> > > > > https://github.com/mfritze/Integrated_Temp/pull/3
> > > > > Commit Summary
> > > > > - removed counter
> > > > > 
> > > > > File Changes
> > > > > - _M_ surveys/views.py
> > > > >   https://github.com/mfritze/Integrated_Temp/pull/3/files#diff-0
> > > > >   (12)
> > > > > 
> > > > > Patch Links:
> > > > > - https://github.com/mfritze/Integrated_Temp/pull/3.patch
> > > > > - https://github.com/mfritze/Integrated_Temp/pull/3.diff
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/mfritze/Integrated_Temp/pull/3.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/mfritze/Integrated_Temp/pull/3#issuecomment-52556107>.
> > 
> > ## 
> > 
> > _Yathi_
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mfritze/Integrated_Temp/pull/3#issuecomment-52697665.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mfritze/Integrated_Temp/pull/3#issuecomment-52698599.

## 

_Yathi_

**Comment by mviz** [comment]
I will implement that today, then.

For now, I'll add a simple title that shows the game status.

Okay sounds good.

**Pull request closed without merging**
